from enum import Enum


class Department(Enum):
    """
    Enum representing valid departments.
    """
    MATHEMATICS = "Mathematics"
    PHYSICS = "Physics"
    CHEMISTRY = "Chemistry"
    COMPUTER_SCIENCE = "Computer Science"
    BIOLOGICAL_SCIENCES = "Biological Sciences"
    ENGLISH = "English Language and Literature"
    HISTORY = "History"
    ECONOMICS = "Economics"
    BUSINESS_ADMINISTRATION = "Business Administration"
    PSYCHOLOGY = "Psychology"
    SOCIOLOGY = "Sociology"
    ENGINEERING = "Engineering"
    ART_AND_DESIGN = "Art and Design"
    MUSIC = "Music"
    THEATER_ARTS = "Theater Arts"
    PHILOSOPHY = "Philosophy"
    POLITICAL_SCIENCE = "Political Science"
    EDUCATION = "Education"
    ENVIRONMENTAL_SCIENCE = "Environmental Science"
    NURSING = "Nursing"
    LAW = "Law"
    MEDICINE = "Medicine"
    DENTISTRY = "Dentistry"
    ARCHITECTURE = "Architecture"
    PHARMACY = "Pharmacy"
    ASTRONOMY = "Astronomy"
    LINGUISTICS = "Linguistics"
    ANTHROPOLOGY = "Anthropology"
    COMPUTER_ENGINEERING = "Computer Engineering"
    ELECTRICAL_ENGINEERING = "Electrical Engineering"
    MECHANICAL_ENGINEERING = "Mechanical Engineering"
    CIVIL_ENGINEERING = "Civil Engineering"
    CHEMICAL_ENGINEERING = "Chemical Engineering"
    MATERIALS_SCIENCE = "Materials Science"
    STATISTICS = "Statistics"
    PUBLIC_HEALTH = "Public Health"
    SOCIAL_WORK = "Social Work"
    INTERNATIONAL_RELATIONS = "International Relations"
    MEDIA_STUDIES = "Media Studies"
    RELIGIOUS_STUDIES = "Religious Studies"
